development:
  react_cors: true
  database:
    table: asira_db
    username: asirauser
    password: asirapass
    host: "127.0.0.1"
    port: "5432"
    maxlifetime: 30
    idle_conns: 10
    open_conns: 100
    sslmode: disable
    logmode: true
    timezone: Asia/Jakarta
  kafka:
    host: "10.148.0.3"
    port: "9092"
    user: user
    pass: oRB5KjfuHdXc
    client_id: asira
    sasl: true
    log_verbose: true
    topics:
      produces:
        for_lender: asira_borrower_to_lender
      consumes:
        for_borrower: asira_lender_to_borrower
  clients:
    admin: Z3JhZGlvczp1bHRpbXVz
    android: YW5kcm9rZXk6YW5kcm9zZWNyZXQ= # androkey:androsecret
  jwt:
    duration: 10080 # in minutes
    jwt_secret: sXQ8jUMpueOvN5P3cdCR
  mailer:
    host : smtp.gmail.com
    port : 587
    email : apranta123@gmail.com
    password : Animajid01
  messaging:
    key: clientkey
    secret: clientsecret
    url: http://asira.ayannah.com/api-messaging
    client_auth: /clientauth
    sms: /client/message_sms_send
    push_notification: /client/message_notification_send
    testing_fcm_token: dtRiFA0U7tE:APA91bGURmGuJLLD0Y_PdhHvFj3haiq8jj8haAfaw94yH0j-Jj6TiGM4wzRHmoLUhihlXKLUF7iFAsAalXzrUVLEVbbtK57_wVYCu2jhameVoG13rc1HgIM6xanEMlApnuwSmURdcdz1
staging:

production: