development:
  react_cors: true
  passphrase: BpLnfgDsc3WD9F3qap394rjd239smsdk
  baseurl: "https://ayannah.co.id"
  database:
    table: asira_db
    username: asirauser
    password: asirapass
    host: "127.0.0.1"
    port: "5432"
    maxlifetime: 30
    idle_conns: 10
    open_conns: 100
    sslmode: disable
    logmode: true
    timezone: Asia/Jakarta
  kafka:
    host: "10.148.0.3"
    port: "9092"
    user: user
    pass: oRB5KjfuHdXc
    client_id: asira
    sasl: true
    log_verbose: true
    topics:
      produces: asira_backend
      consumes: asira_backend
  clients:
    admin: Z3JhZGlvczp1bHRpbXVz
    android: YW5kcm9rZXk6YW5kcm9zZWNyZXQ= # androkey:androsecret
  jwt:
    duration: 10080 # in minutes
    jwt_secret: sXQ8jUMpueOvN5P3cdCR
  mailer:
    host : smtp.gmail.com
    port : 587
    email : infra.ayannah@gmail.com 
    password : jakarta2019
  messaging:
    key: clientkey
    secret: clientsecret
    url: http://asira.ayannah.com/api-messaging
    client_auth: /clientauth
    sms: /client/message_sms_send
    push_notification: /client/message_notification_send
    list_notification: /client/message_notification
    otp_secret: KMndM2vURIGoe1jgzYOA6RTa8qzB5k
  s3:
    debug_mode: 1
    region: id-tbs
    access_key: J2BYZXZ43VPZ27V4TCP3
    secret_key: s0yHeS/eBvjmyshVckbNqVWnTKwhnaP6kYBpFBHk
    host: https://bucket.cloud.lintasarta.co.id:8082
    bucket_name: bucket-ayannah
  northstar:
    secret: Ym9ycm93ZXJrZXk6Ym9ycm93ZXJzZWNyZXQ=
    topic: northstar_logger
    send: true
    
staging:

production: